apiVersion: v1
kind: Namespace
metadata:
  name: endpoints
  labels:
    app.kubernetes.io/name: endpoints
    app.kubernetes.io/part-of: transcripts-v2
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/part-of: transcripts-v2
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/name: apps
    app.kubernetes.io/part-of: transcripts-v2