apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: endpoints
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
    spec:
      containers:
      - name: gateway
        image: transcripts/gateway:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "INFO"
        - name: TRANSCRIPTION_API_URL
          value: "http://transcription-api.endpoints.svc.cluster.local:8000"
        - name: ORCHESTRATION_API_URL
          value: "http://orchestration-api.endpoints.svc.cluster.local:8000"
        - name: WEBHOOK_API_URL
          value: "http://webhook-api.endpoints.svc.cluster.local:8000"
        envFrom:
        - configMapRef:
            name: gateway-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5