apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gateway

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/component: gateway
  app.kubernetes.io/name: gateway