apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-build-
  namespace: argo-workflows
spec:
  entrypoint: test-build-gateway
  arguments:
    parameters:
    - name: git-url
      value: "https://github.com/mzakany23/video-to-transcript.git"
    - name: git-revision
      value: "v2"
    - name: registry
      value: "docker-registry.infrastructure.svc.cluster.local:5000"
    - name: tag
      value: "test-latest"

  templates:
  - name: test-build-gateway
    steps:
    - - name: checkout
        template: git-checkout
    - - name: build-gateway
        template: build-and-push-service
        arguments:
          parameters:
          - name: service-name
            value: "gateway"
          - name: dockerfile
            value: "deploy/docker/images/api/gateway.Dockerfile"

  - name: git-checkout
    container:
      image: alpine/git:latest
      command: [sh, -c]
      args: ["git clone {{workflow.parameters.git-url}} /workspace && cd /workspace && git checkout {{workflow.parameters.git-revision}}"]
      workingDir: /workspace
      volumeMounts:
      - name: workspace
        mountPath: /workspace

  - name: build-and-push-service
    inputs:
      parameters:
      - name: service-name
      - name: dockerfile
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
      - --context=/workspace
      - --dockerfile=/workspace/{{inputs.parameters.dockerfile}}
      - --destination={{workflow.parameters.registry}}/transcripts/{{inputs.parameters.service-name}}:{{workflow.parameters.tag}}
      - --insecure
      - --skip-tls-verify
      volumeMounts:
      - name: workspace
        mountPath: /workspace

  volumeClaimTemplates:
  - metadata:
      name: workspace
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 2Gi