# Development deployment configuration
version: '3.8'

services:
  # Development API Gateway
  gateway:
    build:
      context: ../../..
      dockerfile: deploy/docker/images/api/gateway.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GATEWAY_TRANSCRIPTION_SERVICE_URL=http://transcription-api:8001
      - GATEWAY_WEBHOOK_SERVICE_URL=http://webhook-api:8002
      - GATEWAY_ORCHESTRATION_SERVICE_URL=http://orchestration-api:8003
      - GATEWAY_CORS_ORIGINS=*
    depends_on:
      - transcription-api
      - webhook-api
      - orchestration-api
    networks:
      - transcription-dev
    volumes:
      - ../../../:/app/src:ro  # Mount source for development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # Development Transcription API
  transcription-api:
    build:
      context: ../../..
      dockerfile: deploy/docker/images/api/transcription-api.Dockerfile
    ports:
      - "8001:8001"
    environment:
      - TRANSCRIPTION_ENVIRONMENT=development
      - TRANSCRIPTION_JOB_RUNNER=local
      - TRANSCRIPTION_STORAGE_PROVIDER=local
      - TRANSCRIPTION_TRANSCRIPTION_PROVIDER=openai
      - TRANSCRIPTION_LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../../../data:/app/data
      - ../../../:/app/src:ro
    networks:
      - transcription-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Development Webhook API
  webhook-api:
    build:
      context: ../../..
      dockerfile: deploy/docker/images/api/webhook-api.Dockerfile
    ports:
      - "8002:8002"
    environment:
      - WEBHOOK_ENVIRONMENT=development
      - WEBHOOK_JOB_RUNNER=local
      - WEBHOOK_STORAGE_PROVIDER=local
      - WEBHOOK_LOG_LEVEL=DEBUG
      - DROPBOX_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
    volumes:
      - ../../../data:/app/data
      - ../../../:/app/src:ro
    networks:
      - transcription-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]

  # Development Orchestration API
  orchestration-api:
    build:
      context: ../../..
      dockerfile: deploy/docker/images/api/orchestration-api.Dockerfile
    ports:
      - "8003:8003"
    environment:
      - ORCHESTRATION_ENVIRONMENT=development
      - ORCHESTRATION_JOB_RUNNER=local
      - ORCHESTRATION_STORAGE_PROVIDER=local
      - ORCHESTRATION_LOG_LEVEL=DEBUG
    volumes:
      - ../../../data:/app/data
      - ../../../:/app/src:ro
    networks:
      - transcription-dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]

networks:
  transcription-dev:
    driver: bridge