apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app.kubernetes.io/name: docker-registry
---
# NodePort service for external access during image builds
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-nodeport
  namespace: infrastructure
spec:
  type: NodePort
  ports:
  - name: registry
    port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP
  selector:
    app.kubernetes.io/name: docker-registry