apiVersion: v1
kind: Service
metadata:
  name: webhook-api
  namespace: endpoints
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: webhook-api