apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: transcripts-v2-local

# Base resources to build upon
resources:
  - ../../base
  - local-storage.yaml
  - local-secrets.yaml

# Environment-specific patches and configurations
patches:
  - path: patches/gateway-local.yaml
    target:
      kind: Deployment
      name: gateway

# Image overrides for local development (using cluster-internal registry)
images:
  - name: transcripts/gateway
    newName: docker-registry.infrastructure.svc.cluster.local:5000/transcripts/gateway
    newTag: local-dev
  - name: transcripts/transcription-api
    newName: docker-registry.infrastructure.svc.cluster.local:5000/transcripts/transcription-api
    newTag: local-dev
  - name: transcripts/orchestration-api
    newName: docker-registry.infrastructure.svc.cluster.local:5000/transcripts/orchestration-api
    newTag: local-dev
  - name: transcripts/webhook-api
    newName: docker-registry.infrastructure.svc.cluster.local:5000/transcripts/webhook-api
    newTag: local-dev

# Configuration overrides
configMapGenerator:
  - name: local-config
    literals:
      - ENVIRONMENT=local
      - LOG_LEVEL=DEBUG
      - STORAGE_PROVIDER=local
      - JOB_RUNNER=local

namePrefix: local-
nameSuffix: -v2

labels:
  - pairs:
      environment: local
      version: local-dev