apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgresql

resources:
  - postgresql-deployment.yaml
  - postgresql-service.yaml
  - postgresql-pvc.yaml
  - postgresql-secret.yaml
  - postgresql-configmap.yaml

commonLabels:
  app.kubernetes.io/component: postgresql
  app.kubernetes.io/name: postgresql