apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql