apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: infrastructure
data:
  postgresql.conf: |
    # PostgreSQL configuration for transcripts application
    shared_preload_libraries = 'pg_stat_statements'
    
    # Connection settings
    max_connections = 100
    
    # Memory settings
    shared_buffers = 128MB
    effective_cache_size = 256MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # WAL settings
    wal_buffers = 16MB
    checkpoint_completion_target = 0.9
    wal_writer_delay = 200ms
    
    # Logging
    logging_collector = on
    log_directory = 'pg_log'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'all'
    log_min_duration_statement = 1000
    
    # Performance monitoring
    track_activities = on
    track_counts = on
    track_io_timing = on
    track_functions = pl