apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: infrastructure
type: Opaque
data:
  # transcripts_db (base64 encoded)
  database: dHJhbnNjcmlwdHNfZGI=
  # postgres (base64 encoded)
  username: cG9zdGdyZXM=
  # postgres123 (base64 encoded)
  password: cG9zdGdyZXMxMjM=