apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: endpoints
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: gateway
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: ENVIRONMENT
          value: "local"
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"