apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcription-api
  namespace: endpoints
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: transcription-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transcription-api
    spec:
      containers:
      - name: transcription-api
        image: transcripts/transcription-api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "INFO"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: transcription-secrets
              key: openai-api-key
        - name: STORAGE_PROVIDER
          value: "local"
        - name: STORAGE_BASE_PATH
          value: "/tmp/storage"
        envFrom:
        - configMapRef:
            name: transcription-config
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5