apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app.kubernetes.io/name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: infrastructure
spec:
  type: NodePort
  ports:
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
    nodePort: 30900
  selector:
    app.kubernetes.io/name: minio